package View;

import Model.Entry;
import java.util.ArrayList;
import java.util.List;
import Controler.SearchEntries;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

public class ViewMyEntries extends javax.swing.JFrame {
    int userId;
    SearchEntries se = new SearchEntries();
    List<Entry> myEntries = new ArrayList<>();
    private TitledBorder border;
    Border blackline;
    
    /**
     * Creates new form ViewMyEntries
     */
    public ViewMyEntries(int userId) {
        this.userId = userId;
        myEntries.addAll(se.GetEntriesById(userId));
        initComponents();
        blackline = BorderFactory.createLineBorder(Color.gray);
        PrintEntries();
    }
    
    private void PrintEntries(){
        myEntries.stream().forEach((temp) -> {           
            Box box = Box.createVerticalBox();
            box.add(Box.createRigidArea(new Dimension(5, 5)));
            jPanelEntries.add(box);            
            box.add(new JLabel("Street: " + temp.getAddress()));
            box.add(new JLabel("City: " + temp.getCity()));
            box.add(new JLabel("Country: " + temp.getCountry()));
            box.add(new JLabel("Price: " + temp.getPrice() + "€"));
//            box.add(new JButton(Integer.toString(temp.getId())));
//            box.add(new JButton("Endiaferomai"));
            border = BorderFactory.createTitledBorder(blackline, temp.getTitle());
            box.setBorder(border);
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelEntries = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelEntries.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(jPanelEntries);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelEntries;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
